index:
    path: /ocr
    controller: App\Controller\DefaultController::index
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

get_page:
    path: /getpage
    controller: App\Controller\OcrController::getPage

update_code:
    path: /updatecode
    controller: App\Controller\OcrController::updateCode

update_label:
    path: /updatelabel
    controller: App\Controller\OcrController::updateLabel

update_notes:
    path: /updateNotes
    controller: App\Controller\OcrController::updateNotes

update_annee_n:
    path: /updateAnneeN
    controller: App\Controller\OcrController::updateAnneeN

update_annee_n1:
    path: /updateAnneeN1
    controller: App\Controller\OcrController::updateAnneeN1

get_ligne_ocr:
    path: /getLigneOcr/{matricule}/{annee}
    controller: App\Controller\OcrController::getLigneOcr

get_page_suivante:
    path: /suivant
    controller: App\Controller\OcrController::suivante

get_page_precedente:
    path: /precedent
    controller: App\Controller\OcrController::precedente

update_type_page:
    path: /update-type-page
    controller: App\Controller\OcrController::updateTypePage
